version: '3'

services:
  client:
    image: withotherwords/client
    build: ./client/.
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client/src:/app/src"
