version: '2'

services:
  client:
    image: withotherwords/client
    build: ./client/.
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client/src:/app/src"
